create database Assignment4;
use Assignment4;

create table Employee(
empid integer not null primary key,
emp_name varchar(20),
salary	integer(7),
dept_name varchar(20),
dept_id integer(4));

insert into Employee values(1,"Arun",25000,"PRODUCTION",1);
insert into Employee values(2,"Kiran",15000,"HUMAN RESOURCE",1);
insert into Employee values(3,"Scott",35000,"QUALITY",2);

create table Employee1(
empid integer not null primary key,
emp_name varchar(20),
salary	integer(7),
dept_name varchar(20),
dept_id integer(4));

insert into Employee1 values(1,"Max",16000,"QUALITY",2);
insert into Employee1 values(2,"Jack",30000,"PRODUCTION",3);
insert into Employee1 values(3,"King",10000,"HUMAN RESOURCE",3);

SELECT EMPLOYEE.DEPT_NAME,EMPLOYEE.EMP_NAME FROM EMPLOYEE INNER JOIN EMPLOYEE1 ON EMPLOYEE.DEPT_ID=EMPLOYEE1.DEPT_ID;
SELECT * FROM EMPLOYEE INNER JOIN EMPLOYEE1 ON EMPLOYEE.DEPT_ID=EMPLOYEE1.DEPT_ID;
SELECT DEPT_ID,sum(SALARY) FROM EMPLOYEE group by DEPT_ID;
SELECT EMPLOYEE.DEPT_NAME,EMPLOYEE.EMP_NAME FROM EMPLOYEE RIGHT JOIN EMPLOYEE1 ON EMPLOYEE.DEPT_ID=EMPLOYEE1.DEPT_ID;
SELECT EMPLOYEE.DEPT_NAME,EMPLOYEE.EMP_NAME FROM EMPLOYEE LEFT JOIN EMPLOYEE1 ON EMPLOYEE.DEPT_ID=EMPLOYEE1.DEPT_ID;


select EMP_NAME FROM EMPLOYEE UNION select EMP_NAME FROM EMPLOYEE1;
SELECT EMP_NAME FROM EMPLOYEE WHERE SALARY =(SELECT SALARY FROM EMPLOYEE WHERE EMP_NAME='ARUN');
SELECT EMP_NAME FROM EMPLOYEE WHERE DEPT_NAME=(SELECT DEPT_NAME FROM EMPLOYEE1 WHERE EMP_NAME='JACK');
select EMP_NAME FROM EMPLOYEE WHERE SALARY IN (SELECT MIN(SALARY) FROM EMPLOYEE);
UPDATE EMPLOYEE SET SALARY=15000 WHERE EMP_NAME='MAX';

